# Generated by Django 4.0.6 on 2022-08-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0002_genericfileupload_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfileupload',
            name='file_upload',
            field=models.FileField(upload_to='files/'),
        ),
    ]
