# Generated by Django 4.0.6 on 2022-08-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0003_alter_genericfileupload_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericfileupload',
            name='uploader',
        ),
    ]
