# Generated by Django 4.0.6 on 2022-08-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_user', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
