# Generated by Django 4.0.6 on 2022-08-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_user', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=60, verbose_name='First Name .'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=60, verbose_name='Last Name .'),
            preserve_default=False,
        ),
    ]
