# Generated by Django 4.0.6 on 2022-08-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_user', '0006_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email .'),
        ),
    ]
